### ISSUE TITLE
IMPORT FAILED: LCM_Inpaint-Outpaint_Comfy

### ISSUE THREAD

**Issue by RaduPrusan** [taabata/LCM_Inpaint-Outpaint_Comfy#14]
Traceback (most recent call last):
  File "F:\AI\ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\__init__.py", line 1, in <module>
    from .LCM_Nodes import NODE_CLASS_MAPPINGS
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\LCM_Nodes.py", line 15, in <module>
    from .LCM.LCM_lora_inpaint import LCM_inpaint_final
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\LCM\LCM_lora_inpaint.py", line 27, in <module>
    from diffusers.loaders import FromSingleFileMixin, IPAdapterMixin, LoraLoaderMixin, TextualInversionLoaderMixin
ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (F:\AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\loaders.py)

Cannot import F:\AI\ComfyUI\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy module for custom nodes: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (F:\AI\ComfyUI\python_embeded\Lib\site-packages\diffusers\loaders.py)

**Comment by taabata** [comment]
I think you might need to update the diffusers library

**Comment by izonewonyoung** [comment]
> I think you might need to update the diffusers library

ImportError:cannot import name 'AsymmetricAutoencoderKL' from diffusers
I have a similar problem.Can you tell me how to update the diffusers library?Thank you so much!!!

**Comment by emourdavid** [comment]
I have same issue. All nodes and Comfyui is latest version. Please tell me how to update diffusers library?

from diffusers.loaders import FromSingleFileMixin, LoraLoaderMixin, TextualInversionLoaderMixin, IPAdapterMixin
ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (xxx\ ComfyUI\venv\lib\site-packages\diffusers\loaders.py)

**Comment by emourdavid** [comment]
I know how to update Diffuser to fix this issue.

- Go to activate the environment like this (venv) E:\1.ext_tools\ComfyUI> by run venv\Script\activate in cmd of comfyui folder
- run command >> pip install diffusers -U  and it shows detail like below


Downloading diffusers-0.24.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 7.5 MB/s eta 0:00:00
Downloading huggingface_hub-0.19.4-py3-none-any.whl (311 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.7/311.7 kB 6.4 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, diffusers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.17.3
    Uninstalling huggingface-hub-0.17.3:
      Successfully uninstalled huggingface-hub-0.17.3
  Attempting uninstall: diffusers
    Found existing installation: diffusers 0.21.4
    Uninstalling diffusers-0.21.4:
      Successfully uninstalled diffusers-0.21.4
Successfully installed diffusers-0.24.0 huggingface-hub-0.19.4


Good luck. I think can close this issue

**Comment by ChristophGri** [comment]
i get this error too still. Updated diffusers but i still get this error


File "C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\__init__.py", line 1, in <module>
    from .LCM_Nodes import NODE_CLASS_MAPPINGS
  File "C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\LCM_Nodes.py", line 15, in <module>
    from .LCM.stable_diffusion_reference_img2img import StableDiffusionImg2ImgPipeline_reference
  File "C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\LCM\stable_diffusion_reference_img2img.py", line 23, in <module>
    from diffusers.loaders import FromSingleFileMixin, LoraLoaderMixin, TextualInversionLoaderMixin, IPAdapterMixin
ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders.py)

Cannot import C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy module for custom nodes: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders.py)
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint_Outpaint_Comfy\__init__.py", line 1, in <module>
    from .LCM_Nodes import NODE_CLASS_MAPPINGS
  File "C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint_Outpaint_Comfy\LCM_Nodes.py", line 15, in <module>
    from .LCM.stable_diffusion_reference_img2img import StableDiffusionImg2ImgPipeline_reference
  File "C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint_Outpaint_Comfy\LCM\stable_diffusion_reference_img2img.py", line 23, in <module>
    from diffusers.loaders import FromSingleFileMixin, LoraLoaderMixin, TextualInversionLoaderMixin, IPAdapterMixin
ImportError: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders.py)

Cannot import C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint_Outpaint_Comfy module for custom nodes: cannot import name 'IPAdapterMixin' from 'diffusers.loaders' (C:\Users\Admin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders.py)
